# Site settings
title: Discovery and Exploration
header-img: img/home-bg.jpg
email: prateep.gedupudi@gmail.com
description: "Discovery and Exploration: Knowing and Doing Anything"
baseurl: ""
url: "http://prateep.info"
twitter_username: prateepgedupudi
github_username:  prateepgedupudi
facebook_username:  prateep.gedupudi
youtube_username: PrateepGedupudi
linkedin_username: prateepgedupudi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
