# Site settings
title: Prateep
sub-title: Know to do
header-img: img/home-bg.jpg
email: prateep.gedupudi@gmail.com
description: "Anything"
baseurl: ""
url: "https://prateepgedupudi.github.io"
twitter_username: prateepgedupudi
github_username:  prateepgedupudi
facebook_username:  prateep.gedupudi
youtube_username: PrateepGedupudi
linkedin_username: prateepgedupudi
googleplus_username: PrateepGedupudi

# Build settings
future: true
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ["jekyll-paginate","jekyll-sitemap"]
